Public Class Projects

    Private Sub lbProjects_SelectedIndexChanged(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles lbProjects.SelectedIndexChanged
        'Change the big title
        lblTitle.Text = lbProjects.Text
        'Chanegt the textbox contents to copy and pasted text (Need to write myself really)
        Select Case lbProjects.Items.IndexOf(lbProjects.Text)
            Case 0
                txtContents.Text = "This program will show the Little Man Computer firstly asking the user to input and number and then it will output the result.  The first instruction will copy a the value in the inbox into the accumulator, and then the second instruction will copy the value from the accumulator and put it into the Outbox." + vbCrLf + "Program" + vbCrLf + "" + vbCrLf + "INP" + vbCrLf + "OUT" + vbCrLf + "HLT" + vbCrLf + "" + vbCrLf + "What you should do" + vbCrLf + " • Copy the program above and paste it into the message box." + vbCrLf + " • Click on the Compile button to turn the program into machine code." + vbCrLf + " • Click the Run button to start the program." + vbCrLf + " • When the program asks, enter anumber in the Inbox, and then press the Enter button." + vbCrLf + "" + vbCrLf + "What you should see" + vbCrLf + " • When the program is compiled, you should see 901 in mailbox 0 and 902 in mailbox 1." + vbCrLf + " • After each command is run the message box will describe the current instruction." + vbCrLf + " • After the INP instruction, the value in the Accumulator will be the same as the value in the Inbox." + vbCrLf + " • After the OUT instruction, the Outbox will have the same vale as the accumulator" + vbCrLf + " • The last instruction has the value of 0, this tells the program to stop executing."
            Case 1
                txtContents.Text = "The following program will show you how to Load and Save values." + vbCrLf + "Program" + vbCrLf + "" + vbCrLf + "INP" + vbCrLf + "STA FIRST" + vbCrLf + "INP" + vbCrLf + "STA SECOND" + vbCrLf + "LDA FIRST" + vbCrLf + "OUT" + vbCrLf + "LDA SECOND" + vbCrLf + "OUT" + vbCrLf + "HLT" + vbCrLf + "FIRST DAT" + vbCrLf + "SECOND DAT" + vbCrLf + "" + vbCrLf + "What you should do" + vbCrLf + " • Copy the program into the message box" + vbCrLf + " • Click on the Compile button to turn it into Machine Code." + vbCrLf + " • Click the Run button to start the program." + vbCrLf + " • When the program asks, enter numbers in the Inbox', and then press the Enter button." + vbCrLf + "" + vbCrLf + "What you should see" + vbCrLf + " • When the program is compiled, you should see the instructions 901, 309, 901, 310, 509, 902, 510, 902." + vbCrLf + " • The tenth and eleventh instructions in your program are Data and there names have been asigned to a specific address." + vbCrLf + " • When you click on Run the Message Box will describe the actions of each instruction." + vbCrLf + " • After the first Input instruction, the user will be prompted and then once a valid value has been entered it will be copied to the accumulator." + vbCrLf + " • After the Store instruction, the value inputted is copied from the accumulator to address 09 -- 3 is the store instruction and 09 refers to the address to store into." + vbCrLf + " • Then you will be prompted to input another value (its best to use a different value than the first)." + vbCrLf + " • Now it will be stored into address 10." + vbCrLf + " • Now the program will Load the value in address 9 (The first number you inputed) - 5 refered to the Load instruction and 09 refers to the address to load.  We have to keep loading and storing values as the accumulator can only contain one value at a time." + vbCrLf + " • On the next line we will Output the value we just loaded."
            Case Else
                txtContents.Text = "In total there are 9 different instructions that can be used by the Little Man Computer which usually are follwoed by a address or a variable name which needs to be defined first. Each instruction is the same as a three digit instruction. Usually the first digit represents the instruction and the second and third refer to the address from 00 to 99." + vbCrLf + vbCrLf + "Addition" + vbCrLf + "Mnemonic: ADD" + vbCrLf + "Machine Code: 1**" + vbCrLf + "This instruction loads the contents of the given address and then adds it to the value in the accumulator. The contents in the given address are not changed." + vbCrLf + vbCrLf + "Subtract" + vbCrLf + "Mnemonic: SUB" + vbCrLf + "Machine Code: 2**" + vbCrLf + "This instruction loads the contents of the given address and then subtracts the value from the value in the accumulator. The contents of the given address are not changed." + vbCrLf + vbCrLf + "Store" + vbCrLf + "Mnemonic: STA" + vbCrLf + "Machine Code: 3**" + vbCrLf + "This instructions stores the valeu in the accumulator in the gievn address without chnaging the value in the accumulator." + vbCrLf + vbCrLf + "Load" + vbCrLf + "Mnemonic: LDA" + vbCrLf + "Machine Code: 5**" + vbCrLf + "This instruction loads the contents of the given address into the accumulator without changing the value in the given address." + vbCrLf + vbCrLf + "Branch Always" + vbCrLf + "Mnemonic: BRA" + vbCrLf + "Machine Code: 6**" + vbCrLf + "This instruction changes the current address to the given address." + vbCrLf + vbCrLf + "Branch if 0" + vbCrLf + "Mnemonic: BRZ" + vbCrLf + "Machine Code: 9**" + vbCrLf + "If the value in the accumulator is equal to 0 then we change the address to the address given." + vbCrLf + vbCrLf + "Branch if positive" + vbCrLf + "Mnemonic: BRP" + vbCrLf + "Machine Code: 8**" + vbCrLf + "If the value in the accumulator is zero or positive then we change the address to the address given." + vbCrLf + vbCrLf + "Input" + vbCrLf + "Mnemonic: INP" + vbCrLf + "Machine Code: 901" + vbCrLf + "Pauses the execution of the program until the user inputs a 3 digit number." + vbCrLf + vbCrLf + "Output" + vbCrLf + "Mnemonic: OUT" + vbCrLf + "Machine Code: 902" + vbCrLf + "Copies the value in the accumulator into the Outbox." + vbCrLf + vbCrLf + "Halt" + vbCrLf + "Mnemonic: HLT" + vbCrLf + "Machine Code: 000" + vbCrLf + "Stops the execution of the program." + vbCrLf + vbCrLf + "Data" + vbCrLf + "Mnemonic: DAT" + vbCrLf + "Machine Code: ***" + vbCrLf + "Sets a location in memory to the given value."
        End Select
    End Sub

    Private Sub lblCopyright_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles lblCopyright.Click
        Process.Start("http://matttt.me/projects/lmc") 'Open my website
    End Sub

    Private Sub Projects_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        txtContents.SelectionStart = 0 'Unselect the projects textbox
        txtContents.SelectionLength = 0
        txtContents.ScrollToCaret()
        lbProjects.Focus()
    End Sub

    Private Sub txtContents_MouseDown(ByVal sender As System.Object, ByVal e As System.Windows.Forms.MouseEventArgs)
        txtContents.SelectionLength = 0 'Keep it unselected
        txtContents.ScrollToCaret()
        lbProjects.Focus()
    End Sub

End Class